### ISSUE TITLE
mslr_test reports varying MSLRT test statistics for same data

### ISSUE THREAD

**Issue by SebVen** [benmarwick/cvequality#3]
The `mslr_test()` function appears to report different MSLRT test statistics when re-run. This is also the case when the seed is set. e.g.

```
set.seed(42)
df <- data.frame(x = c(rnorm(20, 5, 2), rnorm(20, 5, 4)), y = c(rep(1, 20), rep(2, 20)))
mslr_test(nr = 10000, x = df$x, y = df$y)

#First execution
$`MSLRT`
[1] 4.750744

$p_value
[1] 0.02928563

#Second execution
$`MSLRT`
[1] 4.849036

$p_value
[1] 0.02766158
```
Is this behaviour expected?

**Comment by benmarwick** [comment]
Thanks for noting this. I think we can see that it is expected, given the way the function is written with `rnorm()` in there. But I agree with you that it's not desirable, and we would like to be able to set a seed and get identical results each time.  So I've made some changes to the functions in https://github.com/benmarwick/cvequality/commit/64b62c89c5d5628adf09667151bc8a1d0f1308e1, and now they work like this:

```
library(cvequality)

set.seed(42)
df <- data.frame(x = c(rnorm(20, 5, 2), rnorm(20, 5, 4)), y = c(rep(1, 20), rep(2, 20)))

# first run
set.seed(42)
> mslr_test(nr = 10000, x = df$x, y = df$y)
$MSLRT
[1] 5.827931

$p_value
[1] 0.01577366

# can we reproduce it?
set.seed(42)
mslr_test(nr = 10000, x = df$x, y = df$y)
$MSLRT
[1] 5.827931

$p_value
[1] 0.01577366
```

Let's scale it up to see if this is robust: 

```
# repeat it n times to see how the results vary
n <- 1000
reps <- replicate(n, {set.seed(42); mslr_test(nr = 10000, x = df$x, y = df$y)})

# take a look
stat <- unlist(reps[seq(1, length(reps), 2)])
pvals <- unlist(reps[seq(2, length(reps), 2)])

length(unique(stat))
[1] 1

length(unique(pvals))
[1] 1

```
Yes, seems that we've got reproducible output when we set the seed immediately before we compute the statistic. 

Can you update to the current version and let me know if it resolves this issue?

**Comment by SebVen** [comment]
Many thanks for the quick response.
I've updated to version 0.2.0 and this has resolved the issue if `set.seed()` is executed in the same command (as per normal R behaviour). Fellow R users may not expect the requirement for setting the seed for reproducibility of this test statistic, so it may be recommendable to add this to the reference manual.
