### ISSUE TITLE
One sided test for CV

### ISSUE THREAD

**Issue by JauntyJJS** [benmarwick/cvequality#4]
Hi,

I understand that this package is able to do a hypothesis test if CV(Group1) is equal to CV(Group2).
May I ask if this package able to do a hypothesis test of CV(Group1) > CV(Group2) or CV(Group1) < CV(Group2) ?

**Comment by benmarwick** [comment]
This is not formally implemented, but you may be able to infer which side is relevant in the test from visualizing your data.
