### ISSUE TITLE
Interpretation of the test

### ISSUE THREAD

**Issue by jpheffne** [benmarwick/cvequality#7]
Hello! I came across your package when I was looking to compare the variability between two groups. The package is really well detailed, but I don't know if I'm entirely clear on what the test is sensitive to. In particular, it seems that the test is incredibly sensitive to the mean of each group, rather than just the standard deviation in isolation (which is a result of the formula for cv). In the really helpful [how_to_test_CVs.Rmd](https://cran.r-project.org/web/packages/cvequality/vignettes/how_to_test_CVs.html) you write: 

"It looks like the L variable (length) has much greater variation that the others...We see low p-values (rounded to zero in the table the asymptotic test p-value is 8.76610110^{-64}), suggesting that the variation in cv values across different measurements is not due to chance. Length is more variable than the other dimensions of the handaxes."

The way you describe the results of the test suggest that it only focuses on variability in the response, rather than the average of the response. 

But if you look at a simple simulation I ran, you can see the test is incredibly sensitive to the mean of different groups especially if the mean of those groups have different signs: 

```
library(cvequality); library(tidyverse)
x1 <- rnorm(n = 1000, mean = 10, sd = 2)
x2 <- rnorm(n = 1000, mean = -10, sd = 2)

test <- data.frame(x1, x2) %>% pivot_longer(cols = c(x1, x2))
with(test, asymptotic_test(value, name))
```

Could you clarify this issue for me and how to best interpret a significant result from this package given this simulation?

**Comment by jpheffne** [comment]
Hello, I was just wondering if you had a chance to look over my comment. 

I'm really interested in comparing the variability between groups for current and future projects and really appreciate your time and advice on this matter!

**Comment by benmarwick** [comment]
Thanks for following up, glad to hear you found what you needed in the vignette!
