### ISSUE TITLE
Is the equation for M correct?

### ISSUE THREAD

**Issue by justinmcgrath** [benmarwick/cvequality#8]
In this vignette, https://cran.r-project.org/web/packages/cvequality/vignettes/how_to_test_CVs.html, the equation for `M` is summed from `j=1` to `m`. I don't see how this make sense. Should it be the sum from `j=1` to `k`?

**Comment by benmarwick** [comment]
Hi Justin,

Thanks for your comment. I took a closer look and I agree that you are correct. That is my mistake in the vignette. I've fixed it here in GitHub now, and will submit the new version to CRAN shortly. Thank you for letting me know about that error.

Warmly,

Ben
