### ISSUE TITLE
Using the Feltz & Miller Test... considering related/correlated samples?

### ISSUE THREAD

**Issue by freddybrown1984** [benmarwick/cvequality#9]
Hello!
          Apologies of this is obvious or just silly. But...

I am testing different 4 x compression garments, including a custom-fitted pair on a single group (repeated measures design) of n = 15. My hypothesis is that in this sample, the custom fitted garments will provide less variable garment-pressures (as they're designed for each specific individual). 
Looking at the examples from the cvequality package, ([https://cran.r-project.org/web/packages/cvequality/vignettes/how_to_test_CVs.html](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcran.r-project.org%2Fweb%2Fpackages%2Fcvequality%2Fvignettes%2Fhow_to_test_CVs.html&data=05%7C01%7Cad1385%40coventry.ac.uk%7Cb4889f8b2d1e456e8a5a08db5d37eff2%7C4b18ab9a37654abeac7c0e0d398afd4f%7C0%7C0%7C638206267041971533%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=35LIcomMjKuKoosf1uWomqnezI22DKLhPZ6aQ0AcFas%3D&reserved=0)) the Feltz & Miller test is used to assess differences in variance of different dimensions of stone artefacts (Fox and Baker 2006). However, wouldnt this potentially ignore potential correlations between dimsions (a "large" arrowhead will likely also have a greater width/breadth if it has a greater length... it's just "bigger". 
With my example, could/should I treat the different garments like independent groups? Or should I really try and use a test that accounts for the repeated/related nature of the different garment pressures (in the same person)?

Finally... Sokal's test (1980) provides a test to compare the varience of related samples... but only with 2 conditions. The authors note this and suggest: "For more than two characters, there is no exact appropriate test. We suggest Levene's test for homogeneity of variances applied to logarithmically
transformed variables, using a randomized complete blocks design". I could then use multiple instances of the Sokal test, post-hoc, accounting for multiple tests. But surely Levene's test is for independent samples? 
https://watermark.silverchair.com/29-1-50.pdf?token=AQECAHi208BE49Ooan9kkhW_Ercy7Dm3ZL_9Cf3qfKAc485ysgAAAtswggLXBgkqhkiG9w0BBwagggLIMIICxAIBADCCAr0GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMQgBT0S4srEiXcXe3AgEQgIICjiGTcJwFsbXOdvbvPTbD9wn9ERveYuLgP8Po1t20OqEpwEIwvwCRzBZdyjG8EuFfnZO3rNR7aSIaiwbafoUu70_k8VDYes032Q97lbBfWZII4RSDWrg6bHtLtmJc7quxuwIuU6-kS8KDlZ1VAYrx7zpUqARDc8alMECjK6aFuMycPL_v6P30Sr_hnv0jYEyaluKNbYrx5KwmW_e-mm9H8UOGW39T2CJJdK_hsKcMSck-9oM8TZw44yeaYPo0CRDHJW5JwG0PurNCk5IS8yyWvkup6t-jSJ00E1vUB9Skw_kqBMrtJH2ithdquFy6B-AJlQ1ZfHTqZiwxbwH0dEceGdfVjylmrxU0WOcsBzMPiktfcMUlP-8m7pRoMLng7bH6Gry9fFcjvV1JDtQyuXyuA9PWjrpjLLofvKYBVZMGf2LVMX_1c8YM43xJOG26TizKtjDc6mGRCfvABhLyalqsEy7EcN4GBzD59P8iKYtI9xXHx4ZQ0GII1Xn2zh-gRtz1FFNxes42lsTiILlw0c9kev_wTwdpEX-H0hoqduzbAYBkmC_w16E-U-cPaVWWLvA3P208qp1V_J7FVGwqwroUosm2vo3v7zSavn-Z2_pZ58FVxSBNx6xV3UFE2IcQ3D5Gh8srFTXZ1K0ZQo4w-5vCJUI8UZhBIwEp_t8yKbatJtsdlX-hERJv9rqY9m7QBG6KrUFOL6VaU1uWLc7FkSv7b7-7zVP_2eR_d4MrklR_mEDDDC3oNCJpNm-PFPe4nT23_NuOEzI6sQQbBZEaSCye1kuqK56TXzfeFw2Gkx7Q2G1JI7rIcNxpdUEYuTTFSiobdfhATGFAXJLCDZXZ98dDliY69Oe1NUrgJuqJk9sVxQ
Any help would be greatfully received!

**Comment by benmarwick** [comment]
Hi Freddy, I replied to your email on this. Feel free to follow up here or by email.
